# Generated by Django 3.2.4 on 2021-06-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_coustom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_custom',
            name='name',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
