# Generated by Django 3.2.4 on 2021-06-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_coustom', '0002_alter_user_custom_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_custom',
            old_name='is_candidate',
            new_name='iscandidate',
        ),
        migrations.RenameField(
            model_name='user_custom',
            old_name='is_employeer',
            new_name='isemployeer',
        ),
    ]
