# Generated by Django 3.2.4 on 2021-06-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_coustom', '0003_auto_20210617_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_custom',
            name='confirmpass',
        ),
    ]
