# Generated by Django 3.2.4 on 2021-06-17 10:44

from django.db import migrations, models
import django.db.models.deletion
import month.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('is_email_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('institute_id', models.IntegerField(primary_key=True, serialize=False)),
                ('institute_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_link', models.FileField(upload_to='')),
                ('coverletter_text', models.CharField(max_length=250)),
                ('coverletter_link', models.FileField(upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_resume', to='jobseeker.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_day', models.DateField()),
                ('birth_month', month.models.MonthField(help_text='some help...', verbose_name='Month Value')),
                ('birth_year', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('marital_status', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to=None)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='jobseeker.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_profdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=250)),
                ('salary', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profdetail', to='jobseeker.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_id', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_type', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=250)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_edu', to='jobseeker.candidate')),
            ],
        ),
    ]
